# Generated by Django 4.2.9 on 2024-11-08 01:06

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _get_failed_allele_liftover_bad_ref_qs(apps):
    AlleleLiftover = apps.get_model('snpdb', 'AlleleLiftover')
    return AlleleLiftover.objects.filter(error__icontains="not equal to calculated ref from genome")

def _has_failed_allele_liftover_bad_ref(apps):
    qs = _get_failed_allele_liftover_bad_ref_qs(apps)
    return qs.exists()

def _delete_failed_allele_liftover_bad_ref(apps, _schema_editor):
    qs = _get_failed_allele_liftover_bad_ref_qs(apps)
    qs.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0151_one_off_fix_csv_export_quoting"),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["liftover_alleles"]),
                        test=_has_failed_allele_liftover_bad_ref),
        migrations.RunPython(_delete_failed_allele_liftover_bad_ref),
    ]
